config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "about-us", to: "home#about_us", as: :about_us
  get "join-us", to: "home#join_us", as: :join_us
  get "contact-us", to: "home#contact_us", as: :contact_us
  get "team", to: "home#team", as: :team
  get "gallery", to: "home#gallery", as: :gallery
  get "faq", to: "home#faq", as: :faq
  get "courses", to: "home#courses", as: :courses
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact_us.html.erb
<!-- Page Title Banner Start -->
<section class="page_title_banner">
    <div class="container">
        <div class="content">
            <div class="title">
                <h1>Contact Us</h1>
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/tag-2.png" alt="" class="tag">
            </div>
            <div class="educate-tilt"
                data-tilt-options='{ "glare": false, "maxGlare": 0, "maxTilt": 2, "speed": 700, "scale": 1 }'>
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/resources/page_title.png" alt="" class="main_img">
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/circle-lines-2.png" alt="" class="circle_vector">
        </div>
    </div>
</section>
<!-- Page Title Banner End -->

<!-- Contact Area Start -->
<section class="py-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-24 mb-lg-0">
                <h6 class="color-primary mb-8">–––– Contact Form</h6>
                <h2 class="mb-16">Get Started With ABA Therapy<br> We're Here To <span
                        class="fm-sec">Help!</span></h2>
                <p class="mb-32">Together, we can create meaningful change and empower every <br>individual to reach their fullest potential through evidence-based care.</p>
                <form method="post" action="contact.html" class="contact-form form-validator">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="mb-24">
                                <input type="text" class="form-control p_lg" id="name" name="name" required
                                    placeholder="First Name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="mb-24">
                                <input type="text" class="form-control p_lg" id="last-name" name="last-name"
                                    required placeholder="Last Name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="mb-24">
                                <input type="email" class="form-control p_lg" id="email" name="email" required
                                    placeholder="Email">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="mb-24">
                                <input type="text" class="form-control p_lg" id="subject" name="subject"
                                    required placeholder="Subject">
                            </div>
                        </div>
                    </div>
                    <div class="mb-24">
                        <textarea class="form-control p_lg" id="detail-message" name="message" rows="5" required
                            placeholder="Message"></textarea>
                    </div>
                    <div class="text-end">
                        <button type="submit" class="educate-btn"><span class="educate-btn__curve"></span>Send
                            Message</button>
                    </div>
                    <!-- Alert Message -->
                    <div id="alert-message" class="alert-msg"></div>
                </form>
            </div>
            <div class="col-lg-6">
                <div class="educate-tilt"
                    data-tilt-options='{ "glare": false, "maxGlare": 0, "maxTilt": 2, "speed": 700, "scale": 1 }'>
                    <img src="https://uiparadox.co.uk/templates/educate/assets/media/resources/contat.png" alt="">
                </div>
            </div>
        </div>
        <div class="contact_links pt-60">
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact_link_block mb-48 mb-lg-0">
                        <div class="icon">
                            <i class="fal fa-map-marker-alt"></i>
                        </div>
                        <h6 class="dark-gray">Kaleidoscope Kollege, Islamabad, Pakistan</h6>
                    </div>
                </div>
                <div class="col-lg-4">
                    <a href="tel:+923001234567" class="contact_link_block mb-48 mb-lg-0">
                        <div class="icon">
                            <i class="fal fa-phone-alt"></i>
                        </div>
                        <span class="h6">+92 300 123 4567</span>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a href="mailto:aba@kaleidoscopekollege.com" class="contact_link_block">
                        <div class="icon">
                            <i class="fal fa-envelope"></i>
                        </div>
                        <span class="h6">aba@kaleidoscopekollege.com</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Area End -->

app/views/home/courses.html.erb
<!-- Page Title Banner Start -->
<section class="page_title_banner">
  <div class="container">
    <div class="content">
      <div class="title">
        <h1>Course Listing</h1>
        <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/tag-2.png" alt="" class="tag">
      </div>
      <div class="educate-tilt"
        data-tilt-options='{ "glare": false, "maxGlare": 0, "maxTilt": 2, "speed": 700, "scale": 1 }'>
        <img src="https://uiparadox.co.uk/templates/educate/assets/media/resources/page_title.png" alt="" class="main_img">
      </div>
      <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/circle-lines-2.png" alt="" class="circle_vector">
    </div>
  </div>
</section>
<!-- Page Title Banner End -->

<!-- Courses Area Start -->
<section class="py-60">
  <div class="container">
    <div class="filter_row">
      <div class="left_block">
        <div class="select_filter">
          <span class="dark-gray">Short by:</span>
          <select name="select" class="has-nice-select">
            <option value="1">Newest</option>
            <option value="2">Oldest</option>
            <option value="3">Popular</option>
            <option value="4">A-Z</option>
          </select>
        </div>
        <div class="select_filter">
          <span class="dark-gray">Category:</span>
          <select name="select" class="has-nice-select">
            <option value="1">Student Life</option>
            <option value="2">Creative Arts</option>
            <option value="3">Graphic Design</option>
            <option value="4">Economic</option>
          </select>
        </div>
      </div>
      <div class="right_block">
        <h6 class="dark-gray">Showing 1-9 of 50 results</h6>
        <form action="blog-grid-left.html" class="search_bar">
          <button type="submit"><i class="fal fa-search"></i></button>
          <input type="search" class="form-control" placeholder="Search here">
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/ps.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-1.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">Photoshop Course</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-1.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Benny Martin</a>
                  <p>Adobe Embassador</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$45</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/ai.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-2.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">Artificial Intelligence</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-2.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Ethan Wilson</a>
                  <p>AI Expert</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$40</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/desktop.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-1.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">Web Design Course</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-3.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Ava Johnson</a>
                  <p>Web Designer</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$45</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/figma.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-2.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">Figma Course</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-4.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Emma Mitchell</a>
                  <p>Ui Engineer</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$45</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/ai2.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-1.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">Illustrator Course</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-5.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Benny Martin</a>
                  <p>Adobe Embassador</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$45</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="course__card mb-24">
          <div class="course__card__icon">
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/icons/ai3.png" alt="">
          </div>
          <div class="course__card__content">
            <div class="left__block">
              <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/tag-2.png" alt="" class="course_tag">
              <h4 class="mb-4p"><a href="course-detail.html">After Effects Course</a></h4>
              <p class="h6 mb-24">Graphics Design</p>
              <ul class="course_info p-0 mb-32">
                <li><i class="fal fa-presentation"></i>45 Videos</li>
                <li><i class="fal fa-clock"></i>05+ Hours</li>
              </ul>
              <div class="author_card">
                <img src="https://uiparadox.co.uk/templates/educate/assets/media/courses/authors/a-6.png" alt="" class="author_img">
                <div class="author_text_block">
                  <a href="team-detail.html" class="h6 mb-4p">Miller Noah</a>
                  <p>Senior Designer</p>
                </div>
              </div>
            </div>
            <div class="right__block">
              <div class="price_block mb-16">
                <div class="price_vector">
                  <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-group.png" alt="">
                </div>
                <span class="h3 color-white">$45</span>
              </div>
              <a href="course-detail.html" class="educate-btn sm mx-xl-auto me-2"><span
                  class="educate-btn__curve"></span>Buy Now</a>
            </div>
            <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/vector-1.png" alt="" class="bottom_vector">
          </div>
        </div>
      </div>
      <ul class="pagination">
        <li class="page-item"><a href="" class="page-link arrow" aria-label="next"><i
              class="far fa-chevron-left"></i></a></li>
        <li class="page-item"><a class="page-link current" href="">1</a></li>
        <li class="page-item"><a class="page-link" href="">2</a></li>
        <li class="page-item"><a class="page-link" href="">3</a></li>
        <li class="page-item"><a href="" class="page-link arrow" aria-label="next"><i
              class="far fa-chevron-right"></i></a></li>
      </ul>
    </div>
  </div>
</section>
<!-- Courses Area End -->

app/views/home/gallery.html.erb
<!-- Page Title Banner Start -->
        <section class="page_title_banner">
            <div class="container">
                <div class="content">
                    <div class="title">
                        <h1>Gallery</h1>
                        <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/tag-2.png" alt="" class="tag">
                    </div>
                    <div class="educate-tilt"
                        data-tilt-options='{ "glare": false, "maxGlare": 0, "maxTilt": 2, "speed": 700, "scale": 1 }'>
                        <img src="https://uiparadox.co.uk/templates/educate/assets/media/resources/page_title.png" alt="" class="main_img">
                    </div>
                    <img src="https://uiparadox.co.uk/templates/educate/assets/media/shapes/circle-lines-2.png" alt="" class="circle_vector">
                </div>
            </div>
        </section>
        <!-- Page Title Banner End -->

        <!-- Gallery Area Start -->
        <div class="pt-60 pb-40">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-1.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 1</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-2.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 2</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-3.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 3</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-4.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 4</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-5.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 5</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-6.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 6</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-7.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 7</span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6 g_c mb-24">
                        <div class="gallery_card">
                            <img src="https://uiparadox.co.uk/templates/educate/assets/media/gallery/g-8.png" alt="" class="br-5 mb-8">
                            <span class="fm-sec">polaroid # 8</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Gallery Area End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Education" %></title>
        <%= javascript_importmap_tags %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body class="custom-cursor locked">
    <%=render 'shared/preload'%>
     <!-- Main Wrapper Start -->
    <div id="main-wrapper" class="main-wrapper">
      <%=render 'shared/navbar'%>
      <!-- Sticky Header -->
      <div class="stricky-header stricked-menu main-menu">
        <div class="sticky-header__content"></div>
      </div>
      <!-- Header Area End  -->
      <%= yield %>
      <%=render 'shared/footer'%>
    </div>

    <!-- Mobile Menu Start -->
    <div class="mobile-nav__wrapper">
      <div class="mobile-nav__overlay mobile-nav__toggler"></div>
      <div class="mobile-nav__content">
        <span class="mobile-nav__close mobile-nav__toggler"><i class="fa fa-times"></i></span>
        <div class="logo-box">
          <a href="index.html" aria-label="logo image"><img src="https://uiparadox.co.uk/templates/educate/assets/media/logo-light.png" alt="educate"></a>
        </div>
        <div class="mobile-nav__container"></div>
        <ul class="mobile-nav__contact list-unstyled">
          <li>
            <i class="fas fa-envelope"></i>
            <a href="mailto:example@company.com">example@company.com</a>
          </li>
          <li>
            <i class="fa fa-phone-alt"></i>
            <a href="tel:+12345678">+123 (4567) -890</a>
          </li>
        </ul>
        <div class="mobile-nav__social">

          <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
          <a href="https://www.pinterest.com/"><i class="fab fa-pinterest-p"></i></a>
          <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <!-- Mobile Menu End -->

    <div class="search-popup">
      <div class="search-popup__overlay search-toggler"></div>
      <div class="search-popup__content">
        <form role="search" method="get" class="search-popup__form" action="index.html">
          <input type="text" id="search" placeholder="Search Here...">
          <button type="submit"><i class="fal fa-search"></i></button>
        </form>
      </div>
    </div>
    <!-- search-popup -->

    <!-- back-to-top-start -->
    <a href="#" class="scroll-top">
      <svg class="scroll-top__circle" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
    </a>
    <!-- back-to-top-end -->
    </div>
    <script src="https://wowjs.uk/dist/wow.min.js"></script>
    <script>new WOW().init();</script>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <!-- Header Area start -->
    <header>
      <nav class="main-menu">
        <div class="container">
          <div class="main-menu__block">
            <div class="main-menu__left">

              <div class="main-menu__logo">
                <a href="/">
                  <%=image_tag 'logo2.png', style: 'width: 160px'%>
                  <%# <img src="https://uiparadox.co.uk/templates/educate/assets/media/logo.png" alt=""> %>
                </a>
              </div>

              <div class="main-menu__nav">
                <ul class="main-menu__list">
                  <!--
                  <li class="dropdown">
                    <a href="javascript:void(0);" class="active">Home</a>
                    <ul>
                      <li><a href="index.html" class="active">Home 1</a></li>
                      <li><a href="index-2.html">Home 2</a></li>
                    </ul>
                  </li>
                  -->
                  <li class="dropdown">
                    <a href="javascript:void(0);">Course</a>
                    <ul>
                      <li><a href="<%=courses_path%>">Courses Page</a></li>
                      <!--<li><a href="course-detail.html">Course Detail</a></li>-->
                    </ul>
                  </li>
                  <!--
                  <li class="dropdown">
                    <a href="javascript:void(0);">Blog</a>
                    <ul class="sub-menu">
                      <li class="dropdown">
                        <a href="javascript:void(0);">Blog Grid</a>
                        <ul class="sub-menu">
                          <li><a href="blog-grid.html">No Sidebar</a></li>
                          <li><a href="blog-grid-left.html">Left Sidebar</a></li>
                          <li><a href="blog-grid-right.html">Right Sidebar</a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="javascript:void(0);">Blog List</a>
                        <ul class="sub-menu">
                          <li><a href="blog-list-left.html">Left Sidebar</a></li>
                          <li><a href="blog-list-right.html">Right Sidebar</a></li>
                        </ul>
                      </li>
                      <li><a href="blog-detail.html">Blog Detail</a></li>
                    </ul>
                  </li>
                  -->
                  <li class="dropdown ">
                    <a href="javascript:void(0);">Pages</a>
                    <ul>
                      <li><a href="<%=about_us_path%>">About</a></li>
                      <li><a href="<%=team_path%>">Our Teacher</a></li>
                      <!--<li><a href="team-detail.html">Teacher Detail</a></li>-->
                      <li><a href="<%=join_us_path%>">Become Teacher</a></li>
                      <li><a href="<%=gallery_path%>">Gallery</a></li>
                      <li><a href="<%=faq_path%>">Faq's</a></li>
                      <!--<li><a href="login.html">Login</a></li>
                      <li><a href="register.html">Register</a></li>-->
                    </ul>
                  </li>
                  <li><a href="<%=contact_us_path%>">Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="main-menu__right">
              <a href="#" class="main-menu__search search-toggler">
                <i class="fal fa-search"></i>
              </a>
              <a href="login.html" class="main-menu__login">
                <i class="fal fa-user"></i>
              </a>
              <a href="contact.html" class="educate-btn sm d-xl-flex d-none"><span
                  class="educate-btn__curve"></span>Enroll Now</a>
              <a href="#" class="main-menu__toggler mobile-nav__toggler">
                <i class="fa fa-bars"></i>
              </a>
            </div>
          </div>
        </div>
      </nav>
    </header>